{% set version = "1.8.4" %}

package:
    name: flann
    version: {{ version }}

source:
    fn: flann-{{ version }}.tar.gz
    url: https://github.com/mariusmuja/flann/archive/{{ version }}.tar.gz
    md5: 774b74580e3cbc5b0d45c6ec345a64ae

build:
    number: 1
    features:
        - vc9   # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]

requirements:
    build:
        - python  # [win]
        - gcc     # [osx]
        - hdf5
        - cmake
    run:
        - libgcc  # [osx]
        - hdf5

test:
    requires:
        - python {{ environ['PY_VER'] + '*' }}  # [win]

    commands:
        # Verify libraries.
        - test -d $PREFIX/include/flann                                    # [unix]
        - test -f $PREFIX/lib/libflann_s.a                                 # [unix]
        - test -f $PREFIX/lib/libflann.dylib                               # [osx]
        - test -f $PREFIX/lib/libflann.so                                  # [linux]
        - test -f $PREFIX/lib/libflann_cpp_s.a                             # [unix]
        - test -f $PREFIX/lib/libflann_cpp.dylib                           # [osx]
        - test -f $PREFIX/lib/libflann_cpp.so                              # [linux]
        - if not exist %PREFIX%\\Library\\lib\\flann.lib exit 1            # [win]
        - if not exist %PREFIX%\\Library\\lib\\flann_cpp_s.lib exit 1      # [win]
        - if not exist %PREFIX%\\Library\\lib\\flann_s.lib exit 1          # [win]
        - if not exist %PREFIX%\\Library\\bin\\flann.dll exit 1            # [win]
        - if not exist %PREFIX%\\Library\\bin\\flann_cpp.dll exit 1        # [win]
        - if not exist %PREFIX%\\Library\\include\\flann exit 1            # [win]

about:
    home: http://www.cs.ubc.ca/research/flann/
    license: BSD 3-Clause
    license_file: COPYING
    summary: "The Fast Library for Approximate Nearest Neighbors"

extra:
  recipe-maintainers:
    - jakevdp
    - jakirkham
