{% set version = "1.9.2" %}

package:
    name: flann
    version: {{ version }}

source:
    fn: flann-{{ version }}.tar.gz
    url: https://github.com/flann-lib/flann/archive/{{ version }}.tar.gz
    sha256: e26829bb0017f317d9cc45ab83ddcb8b16d75ada1ae07157006c1e7d601c8824
    patches:
        # This serializer workaround for VS 2013 doesn't work correctly in VC9.
        - remove-serializer-workaround.patch
        - fix-find-lz4.patch

build:
    number: 3
    run_exports:
        - {{ pin_subpackage('flann', max_pin='x.x.x') }}

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - make         # [unix]
        - libgomp      # [linux]
    host:
        - hdf5
        - lz4-c
        - llvm-openmp  # [osx]

test:
    commands:
        # Verify libraries exist
        {% set flann_libs = [
                "flann_cpp",
                "flann"
        ] %}
        {% for each_flann_lib in flann_libs %}
        - test -f $PREFIX/lib/lib{{ each_flann_lib }}_s.a                # [unix]
        - test -f $PREFIX/lib/lib{{ each_flann_lib }}.dylib              # [osx]
        - test -f $PREFIX/lib/lib{{ each_flann_lib }}.so                 # [linux]
        - if not exist %PREFIX%\\Library\\bin\\{{ each_flann_lib }}.dll exit 1    # [win]
        - if not exist %PREFIX%\\Library\\lib\\{{ each_flann_lib }}.lib exit 1    # [win]
        - if not exist %PREFIX%\\Library\\lib\\{{ each_flann_lib }}_s.lib exit 1  # [win]
        {% endfor %}
        - test -d $PREFIX/include/flann                 # [not win]
        - if not exist %PREFIX%\\Library\\include\\flann exit 1      # [win]

about:
    home: https://github.com/flann-lib/flann/
    license: BSD-3-Clause
    license_file: COPYING
    summary: "The Fast Library for Approximate Nearest Neighbors"

extra:
  recipe-maintainers:
    - traversaro
    - jakevdp
    - jakirkham
    - djsutherland
    - seanyen
