{% set version = "1.9.1" %}

package:
    name: flann
    version: {{ version }}

source:
    fn: flann-{{ version }}.tar.gz
    url: https://github.com/mariusmuja/flann/archive/{{ version }}.tar.gz
    sha256: b23b5f4e71139faa3bcb39e6bbcc76967fbaf308c4ee9d4f5bfbeceaa76cc5d3
    patches:
        # CMake 3.11 breaks FLANN's existing src/cpp/CMakeLists.txt. See
        # https://github.com/mariusmuja/flann/issues/369 for more information.
        - src-cpp-fix-cmake-3.11-build.patch
        # This serializer workaround for VS 2013 doesn't work correctly in VC9.
        - remove-serializer-workaround.patch

build:
    skip: True  # [win and vc<14]
    number: 1011

requirements:
    build:
        - {{ compiler('cxx') }}  # [not win64]
        - vs2017_win-64  # [win64]
        - cmake
        - make  # [unix]
    host:
        - hdf5
        - llvm-openmp  # [osx]
    run:
        - hdf5

test:
    commands:
        # Verify libraries exist
        {% set flann_libs = [
                "flann_cpp",
                "flann"
        ] %}
        {% for each_flann_lib in flann_libs %}
        - test -f $PREFIX/lib/lib{{ each_flann_lib }}_s.a                # [unix]
        - test -f $PREFIX/lib/lib{{ each_flann_lib }}.dylib              # [osx]
        - test -f $PREFIX/lib/lib{{ each_flann_lib }}.so                 # [linux]
        - if not exist %PREFIX%\\Library\\bin\\{{ each_flann_lib }}.dll exit 1    # [win]
        - if not exist %PREFIX%\\Library\\lib\\{{ each_flann_lib }}.lib exit 1    # [win]
        - if not exist %PREFIX%\\Library\\lib\\{{ each_flann_lib }}_s.lib exit 1  # [win]
        {% endfor %}
        - test -d $PREFIX/include/flann                 # [not win]
        - if not exist %PREFIX%\\Library\\include\\flann exit 1      # [win]

about:
    home: http://www.cs.ubc.ca/research/flann/
    license: BSD-3-Clause
    license_file: COPYING
    summary: "The Fast Library for Approximate Nearest Neighbors"

extra:
  recipe-maintainers:
    - jakevdp
    - jakirkham
    - djsutherland
    - seanyen
